// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Limits } from "./Limits";

export type BackendSettings = { 
/**
 * The git program; empty means git from PATH.
 */
gitPath: string, history: Limits, 
/**
 * False until the settings were saved once. The front end then moves its old copy here.
 */
stored: boolean, };
