// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameCommit = { oid: string, author: string, time: number, summary: string, 
/**
 * The line is not committed yet.
 */
uncommitted: boolean, };
