// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlameCommit } from "./BlameCommit";

export type Blame = { commits: Array<BlameCommit>, 
/**
 * For each line of the file, an index into `commits`.
 */
lines: Array<number>, };
