// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BranchInfo = { name: string, full: string, 
/**
 * local, remote or tag
 */
kind: "local" | "remote" | "tag", oid: string, current: boolean, upstream: string | null, ahead: number, behind: number, subject: string, };
