// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Change = { 
/**
 * A, M, D, R, C, T
 */
status: string, path: string, old_path: string | null, };
