// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

export type ChangeListView = { id: string, name: string, comment: string, active: boolean, changes: Array<Change>, };
