// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitDetails = { oid: string, subject: string, author: string, author_email: string, author_time: number, body: string, };
