// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitFull = { oid: string, parents: Array<string>, subject: string, body: string, author: string, author_email: string, author_time: number, committer: string, committer_email: string, commit_time: number, };
