// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One drawing element. `k`: n=node, e=edge. `d`: u/d direction. `j`: row an arrow jumps to.
 */
export type El = { k: "n" | "e", p: number, o: number, d: "u" | "d", a: boolean, t: boolean, s: boolean, c: number, j?: number, 
/**
 * Rows (upper, lower) of a collapsed fragment; clicking the edge expands it.
 */
x?: [number, number], };
