// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Prompt } from "./Prompt";

export type Event = { "kind": "watch", root: string, repo: number, files: number, } | { "kind": "askpass", prompts: Array<Prompt>, };
