// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileContent = { text: string | null, binary: boolean, size: number, missing: boolean, 
/**
 * Why the content is special, for example a submodule or a Git LFS object that is not downloaded.
 */
note?: string, };
