// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindResult = { oid: string | null, 
/**
 * Row in the current view; `None` when the commit is hidden by the filter or unknown.
 */
row: number | null, 
/**
 * The new row count when finding the commit expanded a collapsed branch.
 */
rowCount: number | null, };
