// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Finish puts the branch into the base.
 */
export type FinishMode = "merge" | "squash" | "rebase";
