// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryEntry = { oid: string, parents: Array<string>, subject: string, author: string, time: number, 
/**
 * A, M, D, R, C, T; empty for a merge commit, which has no file list.
 */
status: string, 
/**
 * The path of the file in this commit.
 */
path: string, oldPath: string | null, };
