// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hunk = { id: string, 
/**
 * The first removed line in HEAD, 1-based. With no removed lines, the line after which the hunk adds.
 */
oldStart: number, oldLines: number, 
/**
 * The first added line in the working tree, 1-based. With no added lines, the line after which the
 * hunk removes.
 */
newStart: number, newLines: number, 
/**
 * Set by the changelists: the changelist of this hunk.
 */
list: string, };
