// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Limits = { 
/**
 * Versions older than this are removed.
 */
days: number, 
/**
 * The store removes the oldest versions when the blobs are larger than this.
 */
maxMb: number, };
