// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeListView } from "./ChangeListView";
import type { Hunk } from "./Hunk";

export type LocalChanges = { lists: Array<ChangeListView>, 
/**
 * Untracked files that are not ignored.
 */
unversioned: Array<string>, 
/**
 * Files with merge conflicts. They are also in a changelist, with status `U`.
 */
conflicts: Array<string>, head: string | null, 
/**
 * The hunks of the files that are in more than one changelist, with the changelist of each hunk.
 */
hunks: { [key in string]: Array<Hunk> }, };
