// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergedBranch = { name: string, oid: string, 
/**
 * The tracked branch, for example `origin/main`.
 */
upstream: string, subject: string, };
