// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeSide = { 
/**
 * None when the side does not have the file (it was deleted or never existed there).
 */
text: string | null, label: string, };
