// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeSide } from "./MergeSide";

export type MergeSides = { path: string, base: MergeSide, 
/**
 * The current branch side ("yours").
 */
ours: MergeSide, 
/**
 * The incoming side ("theirs").
 */
theirs: MergeSide, 
/**
 * A side is binary or larger than the text limit: only a whole side can be taken.
 */
binary: boolean, };
