// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergedBranch } from "./MergedBranch";

export type MergedBranches = { branches: Array<MergedBranch>, 
/**
 * True when git finds the branches itself (`git branch --delete-merged`, Git 2.56 or later).
 */
native: boolean, };
