// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergedBranch = { name: string, oid: string, 
/**
 * The tracked branch, for example `origin/main`.
 */
upstream: string, subject: string, 
/**
 * The worktree that has the branch checked out. Deleting the branch removes this worktree first.
 */
worktree?: string, 
/**
 * The worktree has local changes, so git does not remove it.
 */
worktreeDirty: boolean, 
/**
 * The name looks like a long-lived branch (main, uat, release/1.0 and so on), another worktree
 * has the branch, or `branch.<name>.deleteMerged` is false. The dialog does not choose it at first.
 */
suggestKeep: boolean, };
