// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { OpResult } from "./OpResult";
import type { ViewResult } from "./ViewResult";

export type OpOutcome = { result: OpResult, view: ViewResult, head: string | null, 
/**
 * Submodules whose checked-out commit is not the recorded commit after an operation that moved HEAD.
 */
staleSubmodules: Array<string>, 
/**
 * The kind of the failure when the operation did not succeed.
 */
errorKind?: ErrorKind, };
