// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UndoAction } from "./UndoAction";

export type OpResult = { ok: boolean, message: string, 
/**
 * Files with conflicts when the operation stopped.
 */
conflicts: Array<string>, 
/**
 * What Undo does, in order. Empty when the operation cannot be undone.
 */
undo: Array<UndoAction>, };
