// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

/**
 * One line of a rewrite plan, oldest commit first.
 */
export type PlanEntry = { oid: string, action: Action, 
/**
 * New message for reword, or the combined message for the first commit of a squash group.
 */
message?: string, 
/**
 * A new author, as "Name <email>". The author date stays.
 */
author?: string, };
