// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompt = { id: number, text: string, 
/**
 * A password or a passphrase: the field hides the input.
 */
secret: boolean, 
/**
 * A yes or no question, for example an unknown SSH host key.
 */
confirm: boolean, };
