// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutgoingCommit } from "./OutgoingCommit";

export type PushInfo = { branch: string, remotes: Array<string>, 
/**
 * The remote to push to. None when the repository has no remote.
 */
remote: string | null, remoteBranch: string, 
/**
 * The tracked branch, for example `origin/main`.
 */
upstream: string | null, 
/**
 * The remote branch does not exist yet.
 */
newBranch: boolean, outgoing: Array<OutgoingCommit>, 
/**
 * Commits on the remote branch that are not in the local branch. A push without force is rejected.
 */
behind: number, };
