// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RangeCommit = { oid: string, subject: string, message: string, author: string, authorEmail: string, };
