// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutgoingCommit } from "./OutgoingCommit";

export type RefComparison = { left: string, right: string, 
/**
 * The best common ancestor; None when the histories do not meet.
 */
base: string | null, 
/**
 * Commits in the left ref that the right ref does not have, newest first.
 */
onlyLeft: Array<OutgoingCommit>, onlyRight: Array<OutgoingCommit>, };
