// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteInfo = { name: string, fetchUrl: string, 
/**
 * Set only when it differs from the fetch URL.
 */
pushUrl: string | null, };
