// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoState = { 
/**
 * none, merge, rebase, cherry-pick, revert
 */
operation: "none" | "merge" | "rebase" | "cherry-pick" | "revert", branch: string | null, head: string | null, conflicts: Array<string>, 
/**
 * Number of changed or untracked files in the working tree.
 */
changedFiles: number, 
/**
 * The commit where an interactive rebase stopped for editing.
 */
editing: string | null, 
/**
 * The branch that a rebase in progress rewrites.
 */
rebasing: string | null, };
