// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutgoingCommit } from "./OutgoingCommit";
import type { ReviewComment } from "./ReviewComment";
import type { ReviewFile } from "./ReviewFile";
import type { ReviewSummary } from "./ReviewSummary";

export type ReviewDetail = { summary: ReviewSummary, head: string, baseOid: string, mergeBase: string, 
/**
 * The commits of the branch, newest first.
 */
commitList: Array<OutgoingCommit>, fileList: Array<ReviewFile>, commentList: Array<ReviewComment>, };
