// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Revision = { time: number, path: string, 
/**
 * None when the file did not exist at this time.
 */
blob: string | null, label: string, };
