// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note on a line of the branch version of a file.
 */
export type ReviewComment = { id: string, path: string, 
/**
 * The line in the branch version, 1-based.
 */
line: number, text: string, time: number, 
/**
 * The blob of the file when the note was made.
 */
blob: string, 
/**
 * The file changed since the note was made, so the line can be another line now. The list sets it.
 */
outdated: boolean, };
