// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A review in the list.
 */
export type ReviewSummary = { branch: string, base: string, 
/**
 * The branch is a remote-tracking branch, such as `origin/feature`.
 */
branchIsRemote: boolean, 
/**
 * The base is a remote-tracking branch. Merge cannot move it.
 */
baseIsRemote: boolean, 
/**
 * The branch and the base exist.
 */
exists: boolean, 
/**
 * The base has all the commits of the branch.
 */
merged: boolean, 
/**
 * The commits of the branch that the base does not have.
 */
commits: number, 
/**
 * The commits of the base that the branch does not have.
 */
behind: number, files: number, viewed: number, comments: number, 
/**
 * The files that conflict when the branch merges into the base.
 */
conflicts: Array<string>, 
/**
 * The subject and the time of the last commit of the branch.
 */
subject: string, time: number, };
