// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewFile = { status: string, path: string, oldPath: string | null, viewed: boolean, comments: number, };
