// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeCommit } from "./RangeCommit";

/**
 * The commits from `base` (exclusive) to HEAD, oldest first, ready for a rewrite.
 */
export type RewriteRange = { base: string, entries: Array<RangeCommit>, 
/**
 * Some commits are on a remote branch already; a rewrite needs a force push.
 */
published: boolean, };
