// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { El } from "./El";
import type { RefLabel } from "./RefLabel";

export type Row = { row: number, oid: string, refs: Array<RefLabel>, subject: string, author: string, authorEmail: string, authorTime: number, isHead: boolean, elements: Array<El>, };
