// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

export type StashDetail = { oid: string, 
/**
 * The commit the stash was made on.
 */
base: string, 
/**
 * The commit with the untracked files, if the stash has them.
 */
untrackedOid: string | null, 
/**
 * Tracked changes from `base` to the stash.
 */
changes: Array<Change>, 
/**
 * Untracked files; their content is in `untracked_oid`.
 */
untracked: Array<string>, };
