// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stash = { index: number, oid: string, 
/**
 * The message without the "On <branch>:" prefix.
 */
message: string, branch: string | null, time: number, };
