// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmoduleState } from "./SubmoduleState";

export type Submodule = { path: string, 
/**
 * The commit that the superproject records in its index.
 */
recorded: string, 
/**
 * The commit that is checked out in the submodule. None when it is not initialized.
 */
current: string | null, state: SubmoduleState, 
/**
 * The submodule has local changes of its own.
 */
dirty: boolean, url: string | null, };
