// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagInfo = { name: string, 
/**
 * False for a lightweight tag: a name for a commit, without a message.
 */
annotated: boolean, 
/**
 * The commit that the tag points to.
 */
commit: string, tagger: string, taggerEmail: string, time: number, subject: string, 
/**
 * The message after the subject.
 */
body: string, 
/**
 * The tag has a GPG, SSH or X.509 signature. Rebased Lite does not check it.
 */
signed: boolean, };
