// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ViewResult = { root: string, head: string | null, headOid: string | null, totalCommits: number, rowCount: number, filtered: boolean, collapsed: boolean, recommendedWidth: number, loadMs: number, };
