// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = { path: string, head: string | null, branch: string | null, detached: boolean, bare: boolean, locked: boolean, prunable: boolean, 
/**
 * The worktree that this repository window shows.
 */
current: boolean, main: boolean, };
