// Writes src/file-icons.gen.ts: the icon of each file name and extension, from Material Icon Theme
// (MIT, https://github.com/material-extensions/vscode-material-icon-theme). Run it after an update of
// the package: node scripts/file-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("node_modules/material-icon-theme/package.json", "utf8"));
const m = JSON.parse(readFileSync("node_modules/material-icon-theme/dist/material-icons.json", "utf8"));

// VS Code finds the language of a file by its extension, and the theme maps a language to an icon. The
// extensions of the usual languages, for the extensions that the theme does not list itself.
const LANGUAGES = {
  python: ["py", "pyw", "pyi"],
  typescript: ["ts", "mts", "cts"],
  typescriptreact: ["tsx"],
  javascript: ["js", "mjs", "cjs"],
  javascriptreact: ["jsx"],
  markdown: ["md", "markdown", "mdown"],
  rust: ["rs"],
  go: ["go"],
  java: ["java"],
  c: ["c"],
  cpp: ["cc", "cxx", "hh", "hxx"],
  csharp: ["cs"],
  ruby: ["rb"],
  php: ["php"],
  html: ["html", "htm", "xhtml"],
  css: ["css"],
  scss: ["scss"],
  sass: ["sass"],
  less: ["less"],
  json: ["json"],
  jsonc: ["jsonc"],
  yaml: ["yaml", "yml"],
  xml: ["xml", "xsd"],
  shellscript: ["sh", "bash", "zsh"],
  sql: ["sql"],
  swift: ["swift"],
  "objective-c": ["m"],
  "objective-cpp": ["mm"],
  lua: ["lua"],
  perl: ["pl", "pm"],
  r: ["r"],
  dart: ["dart"],
  powershell: ["ps1", "psm1"],
  bat: ["bat", "cmd"],
  ini: ["ini", "cfg"],
  toml: ["toml"],
  plaintext: ["txt"],
  diff: ["diff", "patch"],
  groovy: ["groovy", "gradle"],
  scala: ["scala"],
  haskell: ["hs"],
  elixir: ["ex", "exs"],
  erlang: ["erl"],
  clojure: ["clj"],
  fsharp: ["fs"],
  vue: ["vue"],
  svelte: ["svelte"],
  graphql: ["graphql", "gql"],
  proto: ["proto"],
  tex: ["tex"],
  log: ["log"],
  csv: ["csv"],
  tsv: ["tsv"],
  properties: ["properties"],
  vb: ["vb"],
};

const file = (id) => m.iconDefinitions[id].iconPath.replace(/^.*\//, "").replace(/\.svg$/, "");
function maps(src) {
  const exts = {};
  for (const [lang, list] of Object.entries(LANGUAGES)) {
    const id = src.languageIds?.[lang];
    if (id) for (const e of list) exts[e] = file(id);
  }
  for (const [e, id] of Object.entries(src.fileExtensions ?? {})) exts[e.toLowerCase()] = file(id);
  const names = {};
  for (const [n, id] of Object.entries(src.fileNames ?? {})) names[n.toLowerCase()] = file(id);
  return { names, exts };
}
const dark = maps(m);
const light = maps(m.light);
const out = `// Generated by scripts/file-icons.mjs from material-icon-theme ${pkg.version} (MIT). Do not edit.
// The values are the names of the SVG files in node_modules/material-icon-theme/icons.

export const ICONS = ${JSON.stringify({ file: file(m.file), dark, light })} as const;
`;
writeFileSync("src/file-icons.gen.ts", out);
console.log(`${Object.keys(dark.exts).length} extensions, ${Object.keys(dark.names).length} names`);
